CREATE LOGIN creditUser WITH PASSWORD = 'seCret01*1';
GO

CREATE USER creditUser FOR LOGIN creditUser;
GO

ALTER SERVER ROLE sysadmin ADD MEMBER [creditUser];
GO

CREATE DATABASE creditDB
GO

USE creditDB;
GO

CREATE TABLE Branch (
    Id INT IDENTITY(1,1),
    Name NVARCHAR(100) NOT NULL,
    Address NVARCHAR(255) NOT NULL
);
GO
ALTER TABLE Branch
ADD CONSTRAINT BranchPK PRIMARY KEY (Id);
GO


CREATE TABLE Client (
    Id INT IDENTITY(1,1),
    FirstName NVARCHAR(100) NOT NULL,
    LastName NVARCHAR(100) NOT NULL,
    Email NVARCHAR(100) NOT NULL,
    BranchId INT
);
GO
ALTER TABLE Client
ADD CONSTRAINT ClientPK PRIMARY KEY (id);
GO
ALTER TABLE Client
ADD CONSTRAINT ClientBranchIdFK FOREIGN KEY (BranchId) REFERENCES Branch(Id);
GO


CREATE TABLE CreditRequest (
    Id INT IDENTITY(1,1),
    ClientId INT,
    Amount DECIMAL(18, 2) NOT NULL,
    RequestDate DATETIME NOT NULL DEFAULT GETDATE(),
    Status NVARCHAR(20) NOT NULL,
    BranchId INT
);
GO
ALTER TABLE CreditRequest
ADD CONSTRAINT CreditRequestPK PRIMARY KEY (Id);
GO
ALTER TABLE CreditRequest
ADD CONSTRAINT CreditRequestStatusCHK CHECK (status IN ('APPROVED', 'REJECTED'));
GO
ALTER TABLE CreditRequest
ADD CONSTRAINT CreditRequestBranchIdFK FOREIGN KEY (BranchId) REFERENCES Branch(Id);
GO
ALTER TABLE CreditRequest
ADD CONSTRAINT CreditRequestClientIdFK FOREIGN KEY (ClientId) REFERENCES Branch(Id);
GO
